---
title: "R Notebook"
---

Problem #1
```{r}
# load data 
setwd("/Users/albertwiryawan/Code/Class_GitRepos/Fall_2020/Econometrics/Problem Set #5/Data")
loanapp = read.table("loanapp.txt")

# attach database to r search path to make it easier to attach columns of tables to variables
attach(loanapp)

approve = V50 
white = V59

#model = lm(approve ~ white)
#summary(model)
#coefficients(model)

# part iii 
hrat = V26
obrat = V27
loanprc = V57
unem = V39
male = V48
married = V9 
dep = V10
sch = V45
cosign = V35
chist= V55
pubrec= V25
mortlat1= V53
mortlat2= V54
vr= V44

#model1 = lm(approve ~ white + hrat +obrat + loanprc + unem + male + married + dep + sch + cosign + chist + pubrec + mortlat1 + mortlat2 + vr)
#coefficients(model1)
#summary(model1)

#part iv

model2 = lm(approve ~ white + hrat +obrat + loanprc + unem + male + married + dep + sch + cosign + chist + pubrec + mortlat1 + mortlat2 + vr + I(obrat * white))

#summary(model2)
#coefficients(model2)
model3 = glm(approve ~ white, family=binomial(link="probit"))
model4 = glm(approve ~ white + hrat + obrat + loanprc + unem + male + married + dep + sch + cosign + chist + pubrec + mortlat1 + mortlat2 + vr, family=binomial(link="probit"))
model5 = glm(approve ~ white, family=binomial(link="logit"))
summary(model5)
```

problem #2
```{r}
setwd("/Users/albertwiryawan/Code/Class_GitRepos/Fall_2020/Econometrics/Problem Set #5/Data")
ceosal1 = read.table("ceosal1.txt")

# attach database to r search path to make it easier to attach columns of tables to variables
attach(ceosal1)


```

